### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by mother2110** [sensepost/SPartan#11]
root:~/enum/SPartan]# python SPartan.py -u http://10.10.10.59:80 -s (master✱) 
Traceback (most recent call last):
  File "SPartan.py", line 25, in <module>
    import argparse,requests,sys,os,threading,bs4,warnings,random
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

Running on Kali 2017.2

**Comment by 9andrea1** [comment]
pip install --upgrade beautifulsoup4

**Comment by securiteinfo** [comment]
pip install --upgrade html5lib
and
pip install --upgrade beautifulsoup4
should solve this problem
