### ISSUE TITLE
Error when running an authenticated scan

### ISSUE THREAD

**Issue by Aajnow** [sensepost/SPartan#15]
global name 'ignore_ssl' is not defined
Verbosity is set to HIGH. Spartan will print all resources found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "SPartan.py", line 496, in run
    self.urlProcessor(self.url)
  File "SPartan.py", line 523, in urlProcessor
    if authed:

NameError: global name 'authed' is not defined

I am setting the credentials using the -l option (-l domain.com\\username:test)
Uncredentialed scan runs just fine.

**Comment by rdrg-ar** [comment]
I got the same error.  Is there a fix or a workaround for this?

**Comment by TestingPens** [comment]
Seems to be the reference to the authed variable. Give it a shot now.
