### ISSUE TITLE
Error when running in Kali 

### ISSUE THREAD

**Issue by thebandit19** [sensepost/SPartan#17]
Hello,  

I'm trying to run Spartan in Kali 2018.4 and i get the following error  : 
SPartan.py:733: SyntaxWarning: name 'authed' is assigned to before global declaration
  global authed
Traceback (most recent call last):
  File "SPartan.py", line 25, in <module>
    import argparse,requests,sys,os,threading,bs4,warnings,random
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

Please advise

**Comment by ankushgoel27** [comment]
i am getting the same error

**Comment by paragonsec** [comment]
I solved it by doing the following:
```
pip install --upgrade beautifulsoup4
```

**Comment by securiteinfo** [comment]
pip install --upgrade html5lib
can solve this issue

**Comment by williamcaput** [comment]
https://github.com/MayankPandey01/Sparty-2.0
