### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by stack00** [sensepost/SPartan#21]
Hi please see the error message below;  need your help in this

root@kali:~/Downloads/SPartan# python SPartan.py --help
SPartan.py:733: SyntaxWarning: name 'authed' is assigned to before global declaration
  global authed
Traceback (most recent call last):
  File "SPartan.py", line 27, in <module>
    from requests_ntlm import HttpNtlmAuth
ImportError: No module named requests_ntlm

**Comment by TestingPens** [comment]
Hi there. Please try: pip install requests_ntlm

**Comment by stack00** [comment]
hi thanks for the reply, i tried it but no luck


root@kali:~/SPartan# pip install requests_ntlm
Requirement already satisfied: requests_ntlm in /usr/local/lib/python3.7/dist-packages (0.2.0)
Requirement already satisfied: python-ntlm3 in /usr/local/lib/python3.7/dist-packages (from requests_ntlm) (1.0.2)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests_ntlm) (2.20.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from python-ntlm3->requests_ntlm) (1.10.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.0.0->requests_ntlm) (1.22)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.0.0->requests_ntlm) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.0.0->requests_ntlm) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.0.0->requests_ntlm) (2018.8.24)
root@kali:~/SPartan# python SPartan.py --help
SPartan.py:733: SyntaxWarning: name 'authed' is assigned to before global declaration
  global authed
Traceback (most recent call last):
  File "SPartan.py", line 27, in <module>
    from requests_ntlm import HttpNtlmAuth
ImportError: No module named requests_ntlm
root@kali:~/SPartan#

**Comment by mengen100** [comment]
Same issue! anyone knows how to fix it?

**Comment by TeddyBlue** [comment]
did anyone fix??

**Comment by williamcaput** [comment]
https://github.com/MayankPandey01/Sparty-2.0
